name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-module:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup tools
        run: |
          sudo apt-get update
          sudo apt-get install -y erofs-utils erofsfuse wget unzip xz-utils
          wget https://github.com/ssut/payload-dumper-go/releases/download/1.3.0/payload-dumper-go_1.3.0_linux_amd64.tar.gz
          tar -xvf payload-dumper-go_1.3.0_linux_amd64.tar.gz
          chmod +x payload-dumper-go

      - name: Download HyperOS
        run: |
          wget https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS3.0.319.0.WBLCNXM/pandora-ota_full-OS3.0.319.0.WBLCNXM-user-16.0-2d01cf4d66.zip
          unzip pandora-ota_full-OS3.0.319.0.WBLCNXM-user-16.0-2d01cf4d66.zip
          rm pandora-ota_full-OS3.0.319.0.WBLCNXM-user-16.0-2d01cf4d66.zip

      - name: Unpack HyperOS
        run: |
          ./payload-dumper-go -o ./ -p product ./payload.bin
          rm payload.bin
          mkdir product
          fsck.erofs product.img --extract=product
          df -h
          free -h

      - name: Assemble module
        run: |
          cp -a ./product/app/MINextpay ./module/system/app/MINextpay
          cp -a ./product/app/MITSMClient ./module/system/app/MITSMClient
          cp -a ./product/app/UPTsmService ./module/system/app/UPTsmService
          cp -a ./product/app/MIUISuperMarket ./module/system/app/MIUISuperMarket
          rm ./module/system/app/.gitkeep

      - name: Package module
        run: |
          cd module/
          zip -r ../MiPay4XiaomiEU.zip *

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: MiPay4XiaomiEU.zip
